production:
 create_from_remote: no
 use.user.selected.activities: false
 use.filing.number: false
 show.patient.confirmation: true

development:
 create_from_remote: no
 use.user.selected.activities: false
 use.filing.number: false
 show.patient.confirmation: true

test: &TEST
 create_from_remote: no
 use.user.selected.activities: yes

cucumber:
  <<: *TEST
